In [2]:
# Welcome to your new notebook
# Type here in the cell editor to add code!


StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 4, Finished, Available, Finished)

# Import Numpy

In [3]:
import numpy as np

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 5, Finished, Available, Finished)

In [4]:
np

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 6, Finished, Available, Finished)

<module 'numpy' from '/home/trusted-service-user/cluster-env/trident_env/lib/python3.10/site-packages/numpy/__init__.py'>

# Creating arrays

In [5]:
np.zeros(7)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 7, Finished, Available, Finished)

array([0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(9)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 8, Finished, Available, Finished)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones(9)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 9, Finished, Available, Finished)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Multi-dimensional arrays

In [8]:
np.random.rand(5)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 10, Finished, Available, Finished)

array([0.65712878, 0.71001608, 0.69608372, 0.25296606, 0.8489822 ])

In [9]:
np.random.rand(5, 4)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 11, Finished, Available, Finished)

array([[0.88970797, 0.0404004 , 0.64145806, 0.66862563],
       [0.62258085, 0.28663301, 0.99243763, 0.91854887],
       [0.22523472, 0.18107138, 0.64677387, 0.2094939 ],
       [0.90173888, 0.39972532, 0.74249969, 0.94928597],
       [0.44795758, 0.98652923, 0.54759181, 0.13291254]])

In [10]:
np.full(10, 3)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 12, Finished, Available, Finished)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
list1 = [2, 4, 6, 8, 10]
list1

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 13, Finished, Available, Finished)

[2, 4, 6, 8, 10]

In [12]:
array1 = np.array(list1)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 14, Finished, Available, Finished)

In [13]:
array1

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 15, Finished, Available, Finished)

array([ 2,  4,  6,  8, 10])

In [14]:
array1[3] = 100

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 16, Finished, Available, Finished)

In [15]:
array1

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 17, Finished, Available, Finished)

array([  2,   4,   6, 100,  10])

In [16]:
np.arange(10)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 18, Finished, Available, Finished)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,3)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 19, Finished, Available, Finished)

array([], dtype=int64)

In [18]:
np.linspace(0, 100, 3)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 20, Finished, Available, Finished)

array([  0.,  50., 100.])

# Multidimensional arrays

In [19]:
np.zeros((5, 2))

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 21, Finished, Available, Finished)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.ones((4,4))

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 22, Finished, Available, Finished)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
n= np.array([[1, 2, 3], 
         [4, 5, 6],
        [7, 8, 9]])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 23, Finished, Available, Finished)

In [22]:
n

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 24, Finished, Available, Finished)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
n[2] = [1, 10, 20]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 25, Finished, Available, Finished)

In [24]:
n

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 26, Finished, Available, Finished)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1, 10, 20]])

In [25]:
n[:, 2] = [9, 6, 3]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 27, Finished, Available, Finished)

In [26]:
n

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 28, Finished, Available, Finished)

array([[ 1,  2,  9],
       [ 4,  5,  6],
       [ 1, 10,  3]])

# Randomly generated arrays

In [27]:
np.random.rand(5, 3)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 29, Finished, Available, Finished)

array([[0.41248631, 0.7147564 , 0.18608721],
       [0.74716401, 0.71525933, 0.05390647],
       [0.94034279, 0.28589656, 0.46820989],
       [0.7887689 , 0.41703611, 0.86313854],
       [0.43265688, 0.35480127, 0.82211933]])

In [28]:
np.random.seed(2)
np.random.rand(5, 2)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 30, Finished, Available, Finished)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.rand(5, 2)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 31, Finished, Available, Finished)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [30]:
np.random.seed(2)
np.random.randn(5, 2)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 32, Finished, Available, Finished)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 33, Finished, Available, Finished)

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element wise operations

In [32]:
a = np.arange(5)
a

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 34, Finished, Available, Finished)

array([0, 1, 2, 3, 4])

In [33]:
# want to add numbers to array

a + 1

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 35, Finished, Available, Finished)

array([1, 2, 3, 4, 5])

In [34]:
a * 2

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 36, Finished, Available, Finished)

array([0, 2, 4, 6, 8])

In [35]:
b = 5 + (a/2)
b

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 37, Finished, Available, Finished)

array([5. , 5.5, 6. , 6.5, 7. ])

In [36]:
c = a + b
c

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 38, Finished, Available, Finished)

array([ 5. ,  6.5,  8. ,  9.5, 11. ])

Comparison Operator

In [37]:
a >= 2

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 39, Finished, Available, Finished)

array([False, False,  True,  True,  True])

In [38]:
a != 4

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 40, Finished, Available, Finished)

array([ True,  True,  True,  True, False])

In [39]:
a>b

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 41, Finished, Available, Finished)

array([False, False, False, False, False])

In [40]:
a[a > b]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 42, Finished, Available, Finished)

array([], dtype=int64)

# Summarizing operations

In [41]:
a.min()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 43, Finished, Available, Finished)

0

In [42]:
a.sum()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 44, Finished, Available, Finished)

10

In [43]:
a.std()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 45, Finished, Available, Finished)

1.4142135623730951

In [44]:
a.max()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 46, Finished, Available, Finished)

4

# Linear Algebra

Vector operations

1. Vector Vector multiplication

In [45]:
u = np.array([2, 4, 5, 6])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 47, Finished, Available, Finished)

In [46]:
v = np.array([1, 0, 0, 2])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 48, Finished, Available, Finished)

In [47]:
u.shape

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 49, Finished, Available, Finished)

(4,)

In [48]:
u.shape[0]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 50, Finished, Available, Finished)

4

In [49]:
v.shape

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 51, Finished, Available, Finished)

(4,)

In [50]:
v.shape[0]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 52, Finished, Available, Finished)

4

In [51]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 53, Finished, Available, Finished)

In [52]:
vector_vector_multiplication(u,v)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 54, Finished, Available, Finished)

14.0

In [53]:
u.dot(v)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 55, Finished, Available, Finished)

14

2. Matrix vector multiplication

In [54]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 56, Finished, Available, Finished)

In [55]:
U

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 57, Finished, Available, Finished)

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [56]:
v = np.array([
    1, 0.5, 2, 1
])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 58, Finished, Available, Finished)

In [57]:
np.vstack(v)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 59, Finished, Available, Finished)

array([[1. ],
       [0.5],
       [2. ],
       [1. ]])

In [58]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 60, Finished, Available, Finished)

In [59]:
matrix_vector_multiplication(U,v)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 61, Finished, Available, Finished)

array([20. ,  6. ,  8.5])

In [60]:
U.dot(v)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 62, Finished, Available, Finished)

array([20. ,  6. ,  8.5])

3. Matrix Matrix multiplication 

In [61]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 63, Finished, Available, Finished)

In [62]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 64, Finished, Available, Finished)

In [63]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))


    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[: , i] = Uvi

    return result



StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 65, Finished, Available, Finished)

In [64]:
matrix_matrix_multiplication(U , V)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 66, Finished, Available, Finished)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [65]:
U.dot(V)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 67, Finished, Available, Finished)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identitity matrix
- square matrix

In [66]:
I = np.eye(3)
I

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 68, Finished, Available, Finished)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
V.dot(I)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 69, Finished, Available, Finished)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Matrix inverse

In [68]:
Vs= V[[0, 1, 2]]
Vs

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 70, Finished, Available, Finished)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [69]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 71, Finished, Available, Finished)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [70]:
Vs_inv.dot(Vs)

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 72, Finished, Available, Finished)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Pandas

In [71]:
import numpy as np
import pandas as pd

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 73, Finished, Available, Finished)

# Dataframes

In [72]:
data = [
    ['Nissan', 'Stanza', 1991 , 138, 4, 'Manual', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'Automatic', 'Sedan', 27150],
    ['Lotus', 'Elise', 2017, 218, 4, 'Manual', 'Convertable', 54990],
    ['GMC', 'Acadia', 2017, 194, 4, 'Automatic', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'Manual', 'Pickup', 32340],

]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders', 'Transmission Type', 'vehicle_style', 'MSRP'
]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 74, Finished, Available, Finished)

In [73]:
df = pd.DataFrame(data, columns= columns)
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 75, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            Manual   
1  Hyundai    Sonata  2017        NaN                 4         Automatic   
2    Lotus     Elise  2017      218.0                 4            Manual   
3      GMC    Acadia  2017      194.0                 4         Automatic   
4   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   Convertable  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [74]:
# create datafrmae with dictionary's 

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 76, Finished, Available, Finished)

# Series

In [75]:
df.Make

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 77, Finished, Available, Finished)

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [76]:
df['Make']

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 78, Finished, Available, Finished)

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [77]:
df[['Make', 'Model', 'MSRP']]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 79, Finished, Available, Finished)

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [78]:
df['id'] = [1, 2, 3, 4, 5]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 80, Finished, Available, Finished)

In [79]:
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 81, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            Manual   
1  Hyundai    Sonata  2017        NaN                 4         Automatic   
2    Lotus     Elise  2017      218.0                 4            Manual   
3      GMC    Acadia  2017      194.0                 4         Automatic   
4   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   Convertable  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [80]:
del df['id']

df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 82, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            Manual   
1  Hyundai    Sonata  2017        NaN                 4         Automatic   
2    Lotus     Elise  2017      218.0                 4            Manual   
3      GMC    Acadia  2017      194.0                 4         Automatic   
4   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   Convertable  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [81]:
# Index

df.index

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 83, Finished, Available, Finished)

RangeIndex(start=0, stop=5, step=1)

In [82]:
df.Make

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 84, Finished, Available, Finished)

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [83]:
df.Make.index

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 85, Finished, Available, Finished)

RangeIndex(start=0, stop=5, step=1)

In [84]:
df.loc[1]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 86, Finished, Available, Finished)

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    Automatic
vehicle_style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [85]:
df.loc[[1, 2]]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 87, Finished, Available, Finished)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         Automatic   
2    Lotus   Elise  2017      218.0                 4            Manual   

  vehicle_style   MSRP  
1         Sedan  27150  
2   Convertable  54990

In [89]:
df.index = ['a', 'b', 'c', 'd', 'e']

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 91, Finished, Available, Finished)

In [90]:
df.loc[['a', 'c']]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 92, Finished, Available, Finished)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a  Nissan  Stanza  1991      138.0                 4            Manual   
c   Lotus   Elise  2017      218.0                 4            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
c   Convertable  54990

In [91]:
df.iloc[[1, 2, 4]]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 93, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
b         Sedan  27150  
c   Convertable  54990  
e        Pickup  32340

In [92]:
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 94, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            Manual   
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
d      GMC    Acadia  2017      194.0                 4         Automatic   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   Convertable  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [93]:
df.reset_index()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 95, Finished, Available, Finished)

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2017      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type vehicle_style   MSRP  
0            Manual         sedan   2000  
1         Automatic         Sedan  27150  
2            Manual   Convertable  54990  
3         Automatic       4dr SUV  34450  
4            Manual        Pickup  32340

In [94]:
df.reset_index(drop=True)
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 96, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            Manual   
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
d      GMC    Acadia  2017      194.0                 4         Automatic   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   Convertable  54990  
d       4dr SUV  34450  
e        Pickup  32340

# Assigning Elements

# Element-wise operations

In [95]:
df['Engine HP'] /2

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 97, Finished, Available, Finished)

a     69.0
b      NaN
c    109.0
d     97.0
e    130.5
Name: Engine HP, dtype: float64

In [96]:
df['Year'] >= 2015

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 98, Finished, Available, Finished)

a    False
b     True
c     True
d     True
e     True
Name: Year, dtype: bool

# Filtering

In [97]:
df[
    df['Year'] >=2015
]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 99, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
d      GMC    Acadia  2017      194.0                 4         Automatic   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
b         Sedan  27150  
c   Convertable  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [98]:
df[
    (df['Make'] == 'Nissan')
]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 100, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a  Nissan    Stanza  1991      138.0                 4            Manual   
e  Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
e        Pickup  32340

In [99]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >=2015)
]

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 101, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
e  Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
e        Pickup  32340

# string operations

In [100]:
df.reset_index()
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 102, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            Manual   
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
d      GMC    Acadia  2017      194.0                 4         Automatic   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   Convertable  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [101]:
'STRr'.lower()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 103, Finished, Available, Finished)

'strr'

In [102]:
df['vehicle_style'].str.lower()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 104, Finished, Available, Finished)

a          sedan
b          sedan
c    convertable
d        4dr suv
e         pickup
Name: vehicle_style, dtype: object

In [103]:
df['vehicle_style'].str.replace(' ', '_').str.lower()

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 105, Finished, Available, Finished)

a          sedan
b          sedan
c    convertable
d        4dr_suv
e         pickup
Name: vehicle_style, dtype: object

In [104]:
df

StatementMeta(, a4a32c4b-449a-4da0-81eb-49df80441e2e, 106, Finished, Available, Finished)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            Manual   
b  Hyundai    Sonata  2017        NaN                 4         Automatic   
c    Lotus     Elise  2017      218.0                 4            Manual   
d      GMC    Acadia  2017      194.0                 4         Automatic   
e   Nissan  Frontier  2017      261.0                 6            Manual   

  vehicle_style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   Convertable  54990  
d       4dr SUV  34450  
e        Pickup  32340

# summerizing operations